my_app_front_recommandation:
    resource: "@MyAppFrontBundle/Resources/config/routing/recommandation.yml"
    prefix:   /recommandation

my_app_front_homepage:
    path:     /hello/{name}
    defaults: { _controller: MyAppFrontBundle:Default:index }
    
recommandation:
    path:     /Front/admin/recommandation
    defaults: { _controller: "MyAppFrontBundle:Recommandation:index" }        

recommandation_show:
    path:     /Front/recommandation/{id}/show
    defaults: { _controller: "MyAppFrontBundle:Recommandation:show" }

recommandation_new:
    path:     /Front/recommandation/new
    defaults: { _controller: "MyAppFrontBundle:Recommandation:new" }

recommandation_create:
    path:     /recommandation/create
    defaults: { _controller: "MyAppFrontBundle:Recommandation:create" }
    methods:  POST

recommandation_edit:
    path:     /recommandation/{id}/edit
    defaults: { _controller: "MyAppFrontBundle:Recommandation:edit" }

recommandation_update:
    path:     /recommandation/{id}/update
    defaults: { _controller: "MyAppFrontBundle:Recommandation:update" }
    methods:  [POST, PUT]

recommandation_delete:
    path:     /Front/recommandation/{id}/delete
    defaults: { _controller: "MyAppFrontBundle:Recommandation:delete" }
    methods:  [POST, DELETE]
    
supprimer_recommandation:
    path: /admin/recommandation/delete/{id}
    defaults: { _controller: "MyAppFrontBundle:Recommandation:supprimer" }
    
affichage_recommandation:
    path: /admin/recommandation/afficher
    defaults: { _controller: "MyAppFrontBundle:Recommandation:afficher" }    
    
ajout_recommandation:
    path:     /ajout
    defaults: { _controller: MyAppFrontBundle:Recommandation:ajout }     
    
inc_recommandation:
    path:     /incrementer/{id}
    defaults: { _controller: MyAppFrontBundle:Recommandation:incrementer }         
    
supp_recommandation:
    path:     /supprimer/{id}
    defaults: { _controller: MyAppFrontBundle:Recommandation:supprime }  
    
modif_recommandation:
    path:     /modifier/{id}
    defaults: { _controller: MyAppFrontBundle:Recommandation:modifier }     
    
affichage:
    path:     /affiche
    defaults: { _controller: MyAppFrontBundle:Recommandation:affiche } 
    
search:
    path:     /search
    defaults: { _controller: MyAppFrontBundle:Recommandation:search }    
    
chart:
    path:     /piechart
    defaults: { _controller: MyAppFrontBundle:Recommandation:chartPie }   
    
chart_compagnie:
    path:     /piechart2
    defaults: { _controller: MyAppFrontBundle:Recommandation:chartPieCompagnie }   
    
chart_compagnie_user:
    path:     /piechartusercomp
    defaults: { _controller: MyAppFrontBundle:Recommandation:chartPieCompagnieuser }      
    
chart_lieu:
    path:     /piechart1
    defaults: { _controller: MyAppFrontBundle:Recommandation:chartPieLieu }     
    
chart_lieu_user:
    path:     /piechartuserlieu
    defaults: { _controller: MyAppFrontBundle:Recommandation:chartPieLieuuser }
    
experience_create:
    path:     /createExp
    defaults: { _controller: MyAppFrontBundle:Experience:create }
    
photo_create:
    path:     /createphoto
    defaults: { _controller: MyAppFrontBundle:Photo:create }
    
experience_show:
    path:     /show
    defaults: { _controller: MyAppFrontBundle:Experience:show }
    
detail_experience:
        path:     /detailexp/{id}
        defaults: { _controller: MyAppFrontBundle:Experience:detail }
        
my_experiences:
        path:     /showMyExperience/{id}
        defaults: { _controller: MyAppFrontBundle:Experience:showMyExperience }
supprimer_experiences:
        path:     /suppExp/{id}
        defaults: { _controller: MyAppFrontBundle:Experience:supprimer }

modifier_experiences:
        path:     /modExp/{id}
        defaults: { _controller: MyAppFrontBundle:Experience:modifier }

commenter_experiences:
        path:     /commenter/{id}
        defaults: { _controller: MyAppFrontBundle:Experience:commenter }	
        
cherche_experiences:
        path:     /cherche
        defaults: { _controller: MyAppFrontBundle:Experience:Recherche }

acceul_front:
    path:     /acceuil
    defaults: { _controller: MyAppFrontBundle:Experience:Recherche }
    
show_chercher_experiences:
        path:     /cherche/{pays}/{categorie}/{min}/{max}/{date}
        defaults: { _controller: MyAppFrontBundle:Experience:RechercheShow }

supprimer_images:
        path:     /suppExp/{id}/{id_exp}
        defaults: { _controller: MyAppFrontBundle:Photo:supprimer }  
        
ajouter_sujet:
    path:     /ajout_sujet
    defaults: { _controller: MyAppFrontBundle:Sujet:Ajouter }  
    
liste_sujet_User:
    path:     /liste_sujets_User
    defaults: { _controller: MyAppFrontBundle:SujetUser:listeSujetUser}
    
supprimer:
    path:    /supp/{id}
    defaults: { _controller: MyAppFrontBundle:SujetUser:supprimer }    


liste_reponse_User:
    path:     /liste_reponse_User/{id}
    defaults: { _controller: MyAppFrontBundle:ReponseUser:listeReponseUser}
    
supprimerRep:
    path:    /suppUser/{id}
    defaults: { _controller: MyAppFrontBundle:ReponseUser:supprimerRep }    
    
liste_sujets:
    path:     /liste_sujets
    defaults: { _controller: MyAppFrontBundle:Sujet:ListeSujets} 
    
ajouter_reponse:
    path:     /ajout_reponse/{id}
    defaults: { _controller: MyAppFrontBundle:Reponse:Ajouter }    
    
liste_reponses:
    path:     /liste_reponses/{id}
    defaults: { _controller: MyAppFrontBundle:Reponse:listeReponse}  
  
recherche:
    path:     /recherche
    defaults: { _controller: MyAppFrontBundle:Sujet:recherche} 
    
Guide:
    path:     /listGuide
    defaults: { _controller: "MyAppFrontBundle:Guide:index" }

Guide_show:
    path:     /{id}/showGuide
    defaults: { _controller: "MyAppFrontBundle:Guide:show" }

Guide_new:
    path:     /newGuide
    defaults: { _controller: "MyAppFrontBundle:Guide:new" }

Guide_create:
    path:     /createGuide
    defaults: { _controller: "MyAppFrontBundle:Guide:create" }

Guide_edit:
    path:     /{id}/editGuide
    defaults: { _controller: "MyAppFrontBundle:Guide:modifier" }

Guide_update:
    path:     /{id}/updateGuide
    defaults: { _controller: "MyAppFrontBundle:Guide:update" }
    requirements: { _method: post|put }

Guide_delete:
    path:     /{id}/deleteGuide
    defaults: { _controller: "MyAppFrontBundle:Guide:delete" }
    requirements: { _method: post|delete } 
    
my_app_front_pdf:
    path:     /pdf
    defaults: { _controller: MyAppFrontBundle:Default:pdf }  
    
Ajout:
    path:     /ajouterNews
    defaults: { _controller: MyAppFrontBundle:Newsletter:Ajout }
    
affich:
    path:     /afficherNews
    defaults: { _controller: MyAppFrontBundle:Mail:new }
    
supprimer:
    path:     /supprimer{id}
    defaults: { _controller: MyAppFrontBundle:Newsletter:supprimer }
    
modifier:
    path:     /modifierNews{id}
    defaults: { _controller: MyAppFrontBundle:Newsletter:Modifier }
    
recherche_news:
    path:     /rechercherNews
    defaults: { _controller: MyAppFrontBundle:Newsletter:Recherche }
AjoutF:
    path:     /ajouterflux
    defaults: { _controller: MyAppFrontBundle:Flux:Ajout }
    
affichF:
    path:     /afficherflux
    defaults: { _controller: MyAppFrontBundle:Flux:Affichage }
    
supprimerF:
    path:     /supprimerflux/{id}
    defaults: { _controller: MyAppFrontBundle:Flux:supprimer }
    
modifierF:
    path:     /modifierflux/{id}
    defaults: { _controller: MyAppFrontBundle:Flux:Modifier }
    
new:
    path:     /newsletter
    defaults: { _controller: MyAppFrontBundle:Flux:news }
    
my_app_mail_succ:
    path: /succ
    defaults: { _controller: MyAppFrontBundle:Mail:index }

 

my_app_mail_form:
    path: /mail
    defaults: { _controller: MyAppFrontBundle:Mail:new }

    

my_app_mail_sendpage:
    path: /sendmail/{personne}
    defaults: { _controller: MyAppFrontBundle:Mail:sendMail }
    
