services:
    my_app_user.registration.form.type:
        class: MyApp\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: myapp_user_registration }
 #       arguments: [@service_id, "plain_value", %parameter%]
            
    my_app_user.resetting.form.type:
        class: MyApp\UserBundle\Form\Type\ResettingFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: myapp_user_resetting }  
            
    my_app_user.registration.form.type:
        class: MyApp\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: myapp_user_registration }
            
    my_app_user.ajout.form.type:
        class: MyApp\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: myapp_user_registration }            
   
    myapp_user.profile.form.type:
        class: MyApp\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: myapp_user_profile }
            
    myapp_user.profile.form.factory:
        class: MyApp\UserBundle\Form\Factory\FormFactory
        arguments: [%fos_user.profile.form.name%]
        arguments: [%fos_user.profile.form.type%]
        arguments: [%fos_user.profile.form.validationGroups%]   
        
    my_user_provider:
        class: "%my_user_provider.class%"
    #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{facebook: facebook_id}]    


#    rkueny.oauth.user_provider:
#        class: %rkueny.oauth.user_provider.class%
#        arguments: ['@fos_user.user_manager', { facebook: facebookId }]
        
parameters:
        #rkueny.oauth.user_provider.class: MyApp\UserBundle\OAuth\UserProvider
        my_user_provider.class: MyApp\UserBundle\Security\FOSUBUserProvider
        